spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate / none / create / create-drop
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  application:
    name: spring-hibernate-postgresql-application
server:
  port: 8082
logging:
  level:
    "[org.springframework.security.web]": TRACE
    root: INFO
    "[io.github.juniperfags.configuration.security]": DEBUG
